[build]
  command = "npm run build"
  publish = "dist"  # Change from 'out' to 'dist' for Astro

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
